apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: notiflex-secrets
  namespace: notiflex
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/yunsoo-gitaiops-project/secrets/notiflex-valkey-addr/versions/latest"
        path: "valkey-addr"
      - resourceName: "projects/yunsoo-gitaiops-project/secrets/notiflex-valkey-password/versions/latest"
        path: "valkey-password"
  secretObjects:
    - secretName: notiflex-secrets
      type: Opaque
      data:
        - objectName: valkey-addr
          key: VALKEY_ADDR
        - objectName: valkey-password
          key: VALKEY_PASSWORD
