apiVersion: v1
kind: ServiceAccount
metadata:
  name: notiflex-api
  namespace: notiflex
  annotations:
    iam.gke.io/gcp-service-account: notiflex-api-sa@yunsoo-gitaiops-project.iam.gserviceaccount.com
